/*
 * This file is generated by jOOQ.
*/
package com.ducnd.mysql;


import com.ducnd.mysql.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in demo
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>demo.user</code>.
     */
    public static final User USER = com.ducnd.mysql.tables.User.USER;
}
